In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
# For conversion
from skimage.color import lab2rgb, rgb2lab, rgb2gray
from skimage import io
# For everything
import torch
import torch.nn as nn
import torch.nn.functional as F
# For our model
import torchvision.models as models
from torchvision import datasets, transforms
# For utilities
import os, shutil, time

use_gpu = torch.cuda.is_available()

In [9]:
base_dir = os.getcwd()
print(base_dir)
train_dir = os.path.join(base_dir, '/volume/dataset/training')
test_dir = os.path.join(base_dir, '/volume/dataset/test')

#Initial Testing
test_image = os.path.join(base_dir, '/volume/initial/grayscale/00000.png')
img = cv2.imread(r'/Users/william/Downloads/initial/grayscale/00000.png')
print(img)

/Users/william/Library/CloudStorage/OneDrive-Personal/Documents/School/Spring 2022/DS 440/Capstone Project/GitHub/src/models
[[[ 96  96  96]
  [ 96  96  96]
  [ 91  91  91]
  ...
  [ 86  86  86]
  [ 85  85  85]
  [ 85  85  85]]

 [[ 91  91  91]
  [ 94  94  94]
  [ 90  90  90]
  ...
  [ 85  85  85]
  [ 85  85  85]
  [ 85  85  85]]

 [[ 92  92  92]
  [ 93  93  93]
  [ 91  91  91]
  ...
  [ 84  84  84]
  [ 85  85  85]
  [ 84  84  84]]

 ...

 [[110 110 110]
  [109 109 109]
  [111 111 111]
  ...
  [152 152 152]
  [151 151 151]
  [151 151 151]]

 [[112 112 112]
  [108 108 108]
  [111 111 111]
  ...
  [153 153 153]
  [145 145 145]
  [152 152 152]]

 [[110 110 110]
  [110 110 110]
  [109 109 109]
  ...
  [155 155 155]
  [153 153 153]
  [151 151 151]]]
